{
    'name': 'Amazon Odoo Connector',
    'version': '11.0.4',
    'category': 'Sales',
    'summary' : 'Integrate & Manage all your Amazon seller account operations from Odoo',
    'author': 'Emipro Technologies Pvt. Ltd.',
    'website': 'http://www.emiprotechnologies.com/',
    'maintainer': 'Emipro Technologies Pvt. Ltd.',
    'depends': ['auto_invoice_workflow_ept', 'delivery', 'web','sale_stock','sale_management'],
    'data': [
             'security/res_groups.xml',
             'security/ir.model.access.csv',
             'view/res_config_view.xml',
             'view/product_brand_view.xml',
             'view/base_browse_node.xml',
             'view/browse_node.xml',
             'view/product_view.xml',
             'view/process_import_export.xml',
             'view/sales_view.xml',
             'report/sale_report_view.xml',
             'view/order_refund_view.xml',
             'view/stock_view.xml',
             'view/invoice_view.xml',
             'view/feed_submission_history.xml',
             'view/amazon_file_process_job.xml',
             'view/amazon_report_wizard.xml',             
             'view/amazon_seller.xml',
             'view/instance_view.xml',                                                
             'view/auto_work_flow_configuration.xml',
             'view/tax_code_view.xml',
             'view/ir_cron.xml',             
             'view/product_wizard_view.xml',
             'view/cancel_order_wizard_view.xml',
             'view/res_country.xml',
             'view/web_templates.xml',
             'view/stock_quant_package.xml',
             'view/stock_warehouse.xml',
             'view/settlement_report.xml',             
             'view/amazon_transaction.xml',      
             'view/delivery.xml',
             'view/active_product_listing_view.xml',
             'view/account_fiscal_position.xml',
             'view/amazon_category.xml',
             'view/amazon_category_data.xml',
             'view/product_attribute.xml',
             'view/ir_sequence.xml',
             'view/amazon_sale_order_report_view.xml',
             'view/stock_picking_seller.xml', 
             'view/account_move_view.xml',
             'view/account_move_line_view.xml',
             'view/stock_move_view.xml',
             'view/file_selection_wizard.xml',
             'view/amazon_operations_ept_view.xml',
             'data/amazon.base.browse.node.ept.csv',
             'data/amazon.uom.type.ept.csv',
             'data/amazon.uom.value.ept.csv',             
             'data/amazon.attribute.ept.csv',
             'data/amazon.attribute.value.ept.csv',
             'data/amazon.tax.code.ept.csv',
             'data/amazon.cspia.warning.ept.csv',
             'data/amazon.payment.type.option.ept.csv',
             'data/amazon.tsd.language.ept.csv',
             'data/amazon.tsd.warning.ept.csv',
             'data/amazon.variation.theme.ept.csv',
             'data/amazon.transaction.type.csv',
            
             'data/import_product_attachment.xml',
             ],
    
    'images': ['static/description/main_screen.jpeg'],
    'installable': True,
    'auto_install': False,
    'pre_init_hook':'version_check',
    'live_test_url':'http://bit.ly/2LYTzKN',
    'application' : True,
    'price': 450.00,
    'license': 'OPL-1',
    'currency': 'EUR',
}
